apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitea
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/rhilconsultants/gitea-operator.git
      revision: openshift-pipelines-training
      directories:
      - path: "gitea-deployment/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: gitea
      source:
        repoURL: https://github.com/rhilconsultants/gitea-operator.git
        targetRevision: openshift-pipelines-training
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: gitea
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true