kind: Gitea
apiVersion: pfe.rhpds.com/v1
metadata:
  name: gitea-demo
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  giteaSsl: true
  giteaAdminUser: opentlc-mgr
  giteaAdminPassword: ""
  giteaAdminPasswordLength: 6
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaCreateUsers: true
  giteaGenerateUserFormat: "user%d"
  giteaUserNumber: 20
  giteaUserPassword: openshift
  giteaMigrateRepositories: true
  giteaWebhookAllowedHostList: '*'
  giteaDisableSsh: false
  giteaSshPort: 2022
  giteaStartSshServer: true
  giteaAllowLocalNetworkMigration: true
  giteaRepositoriesList:
  - repo: https://github.com/magreenberg/httpserver-ci-demo.git
    name: httpserver
    private: false
  - repo: https://github.com/magreenberg/httpserver-ci-cd-demo.git
    name: httpserver-cd
    private: false
