kind: Gitea
apiVersion: pfe.rhpds.com/v1
metadata:
  name: gitea-demo
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  giteaSsl: false
  giteaAdminUser: opentlc-mgr
  giteaAdminPassword: ""
  giteaAdminPasswordLength: 32
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaCreateUsers: true
  giteaGenerateUserFormat: "user%d"
  giteaUserNumber: 2
  giteaUserPassword: openshift
  giteaMigrateRepositories: true
  giteaWebhookAllowedHostList: '*'
  giteaDisableSsh: false
  giteaSshPort: 2022
  giteaStartSshServer: true
  giteaAllowLocalNetworkMigration: true
  giteaRepositoriesList:
  - repo: https://github.com/tal-hason/cd-repo-demo.git
    name: cd-repo-demo
    private: false
  - repo: https://github.com/tal-hason/nodejs-demo-app.git
    name: nodejs-demo-app
    private: false
  - repo: https://github.com/tal-hason/angular-demo-app.git
    name: angular-demo-app
    private: false
  - repo: https://github.com/tal-hason/dotnet-demo-app.git
    name: dotnet-demo-app
    private: false