kind: Namespace
apiVersion: v1
metadata:
  name: gitea
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
